import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {
  SignInButton,
  ClerkProvider,
  SignOutButton,
  UserButton,
  UserProfile,
  currentUser,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <>
              <div className="bg-gray-300 w-screen h-16"></div>
              <div className="w-screen h-10 flex justify-end pr-16">
                {!user && (
                  <SignInButton>
                    <Button className="text-xl" variant="link">
                      sign in
                    </Button>
                  </SignInButton>
                )}

                {!!user && (
                  <SignOutButton>
                    <Button className="text-xl" variant="link">
                      sign out
                    </Button>
                  </SignOutButton>
                )}
              </div>
              {children}
            </>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
