import React from "react";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Image from "next/image";
import Link from "next/link";
import { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "Clothing | FRNR",
  description: "Generated by create next app",
};

export default function Store() {
  return (
    <main className="overflow-hidden">
      <div className="ps-6 overflow-hidden">
        <Breadcrumb className="mt-12">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Home</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Components</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Categories</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Clothing</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>

        <h1 className="mt-12 scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
          Clothing
        </h1>
        <p className="leading-7 [&:not(:first-child)]:mt-6 w-5/12">
          We offer a wide range of designer clothing for all occasions, no
          matter it is a special occasion in life, a casual vacation look or a
          daily working outfit, weve got your back. Choose from our
          well-selected designer brand list including Loewe, Jil Sander, Maison
          Margiela, Burberry and more. Our designer clothing collection covers
          designer tops, skirts, dresses, pants, jackets with different styles
          and colors.
        </p>

        <div className="mt-12 flex justify-between">
          <div className="w-1/12">
            <Accordion type="multiple">
              <AccordionItem value="item-1">
                <AccordionTrigger>categories</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>brands</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger>color</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger>size</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-5">
                <AccordionTrigger>price</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-6">
                <AccordionTrigger>sale</AccordionTrigger>
                <AccordionContent>
                  Yes. It adheres to the WAI-ARIA design pattern.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>

          <div className="flex flex-wrap gap-x-8 w-10/12 h-screen">
            {Array(10)
              .fill(null)
              .map((_, index) => (
                <Link
                  href={"/product"}
                  key={index}
                  className="flex flex-col w-60 h-100 text-center 0"
                >
                  <div className="w-60 h-80">
                    <Image
                      width={500}
                      height={700}
                      alt="image"
                      src={
                        "https://image-cdn.hypb.st/https%3A%2F%2Fs3.store.hypebeast.com%2Fmedia%2Fimage%2Fae%2F6f%2FJacket-13-3-h-f83d5.jpg?fit=max&w=460&q=60"
                      }
                    />
                  </div>
                  <div className="text-left">
                    <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
                      frnr made
                    </h3>
                    <p>graphic t-shirt</p>
                    <div>
                      <h4 className="scroll-m-20 text-xl font-semibold tracking-tight">
                        CAD$100
                      </h4>
                      <span>new</span>
                    </div>
                  </div>
                </Link>
              ))}
          </div>
        </div>
      </div>
    </main>
  );
}
