import React from "react";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: " GRAPHIC T-SHIRT #7 | FRNR",
  description: "Generated by create next app",
};

export default function Product() {
  return (
    <main>
      <div className="px-6">
        <Breadcrumb className="mt-12">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Home</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Components</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Categories</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Outerwear</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>GRAPHIC T-SHIRT #7</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </div>

      <div className="flex justify-between w-screen p-2">
        <div className="flex w-11/12 h-1/2 gap-x-3 mr-12">
          <Image
            src={
              "https://image-cdn.hypb.st/https%3A%2F%2Fs3.store.hypebeast.com%2Fmedia%2Fimage%2Ff6%2Fa8%2Fjacket-2-1-fab7b.jpg?fit=max&w=720&q=90"
            }
            height={10}
            width={700}
            alt="image"
          />
          <Image
            src={
              "https://image-cdn.hypb.st/https%3A%2F%2Fs3.store.hypebeast.com%2Fmedia%2Fimage%2F10%2Feb%2Fjacket-2-5-43e80.jpg?fit=max&w=720&q=90"
            }
            height={10}
            width={700}
            alt="image"
          />
        </div>

        <div className="flex flex-col w-4/12 h-6/6 ml-24 ">
          <div className="mb-12">
            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight">
              FRNR MADE
            </h4>
            <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
              GRAPHIC T-SHIRT #7
            </h3>
            <p className="leading-7 [&:not(:first-child)]:mt-6">CA$150</p>
          </div>

          <div className="mb-24">
            <h3>SIZE</h3>
            <div className="flex mb-5 mt-3 ">
              <Button
                variant={"ghost"}
                className="w-10 h-10 bg-white text-gray-950  flex items-center justify-center mr-3"
              >
                <span>S</span>
              </Button>
              <Button
                variant={"ghost"}
                className="w-10 h-10 bg-white text-gray-950  flex items-center justify-center mr-3"
              >
                <span>M</span>
              </Button>
              <Button
                variant={"ghost"}
                className="w-10 h-10 bg-white text-gray-950  flex items-center justify-center mr-3"
              >
                <span>L</span>
              </Button>
              <Button
                variant={"ghost"}
                className="w-10 h-10 bg-white text-gray-950  flex items-center justify-center mr-3"
              >
                <span>XL</span>
              </Button>
            </div>

            <Link href={"/"} className="underline text-sm">
              size guide
            </Link>
          </div>

          <div className="mb-24">
            <h4>QUANTITY</h4>

            <div className="inline-flex rounded-md shadow-sm mt-3">
              <a
                href="#"
                aria-current="page"
                className="px-4 py-2 text-sm font-medium text-blue-700 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100   dark:bg-gray-300 dark:border-gray-700 dark:text-black dark:hover:text-white dark:hover:bg-cyan-900 dark:focus:text-white"
              >
                -
              </a>
              <a
                href="#"
                className="px-4 py-2 text-sm font-medium text-blue-700 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100   dark:bg-white dark:border-gray-700 dark:text-black "
              >
                3
              </a>
              <a
                href="#"
                className="px-4 py-2 text-sm font-medium text-blue-700 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100   dark:bg-gray-300 dark:border-gray-700 dark:text-black dark:hover:text-white dark:hover:bg-cyan-900 dark:focus:text-white"
              >
                +
              </a>
            </div>
          </div>

          <div className="w-100 flex flex-col  gap-y-5">
            <button className="w-10/12 h-12 bg-cyan-900">Add to Bag</button>
            <button className="w-10/12 h-12 bg-gray-300">
              Continue Shopping
            </button>
          </div>
        </div>
      </div>
    </main>
  );
}
